name: Lint

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check src/ tests/
          ruff format --check src/ tests/
