name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    name: Test

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Setup RabbitMQ
        continue-on-error: true
        run: |
          sudo apt-get install --assume-yes rabbitmq-server

      - name: Install dependencies
        run: |
          uv sync --no-dev --frozen --extra all

      - name: Test with pytest
        run: |
          uv pip install pytest pytest-mock pytest-asyncio pytest-cov pytest-rabbitmq pytest-env
          uv run pytest
        env:
          PYTEST_RABBITMQ_CTL: '/usr/lib/rabbitmq/bin/rabbitmqctl'
          PYTEST_RABBITMQ_SERVER: '/usr/lib/rabbitmq/bin/rabbitmq-server'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
